url: "https://testautomationpractice.blogspot.com/"

form_data:
  name: "Abhijeet Singh"
  email: "abhijeetsingh@xyz.com"
  phone: "9988774456"
  country: "India"
  start_date: "10/01/2025"
  end_date: "10/10/2025"
